# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9s < Formula
  desc "Kubernetes CLI To Manage Your Clusters In Style!"
  homepage "https://k9scli.io/"
  version "0.40.10-custom.1"

  on_macos do
    on_arm do
      url "https://github.com/ventsislav-georgiev/homebrew-k9s/releases/download/v0.40.10-custom.1/k9s_Darwin_arm64.tar.gz"
      sha256 "cc9a2b4b36abbab6f00fd566893232d8a8c78d6a5075857bef2328c8e557ca1c"

      def install
        bin.install "k9s"
      end
    end
  end

  test do
    system "k9s version"
  end
end
